apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycapstone
  labels:
    app: mycapstone
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mycapstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mycapstone
    spec:
      containers:
        - image: sisihliay/capstone
          imagePullPolicy: Always
          name: mycapstone
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mycapstone
  labels:
    app: mycapstone
spec:
  type: LoadBalancer
  selector:
    app: mycapstone
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
